### ISSUE TITLE
lldebugger bootstrap code

### ISSUE THREAD

**Issue by thejustinwalsh** [astrochili/defold-vscode-guide#1]
Working on @ts-defold and came across this guide! Great work!

The following code will let you load lldebugger directly from the extension vs needing to copy it into the runtime directly.

The gist of it is:
- Look for `"tomblind.local-lua-debugger"` in `LUA_PATH`
- Use `loadfile` to load then execute the `lldebugger.lua` file from the extension
- Add it to the `path.loaded` table
- Somewhere later require and start the debugger

A big chunk of the code below is actually working around a few TypeScriptToLua bugs. Haha

You could port this directly to lua, as it isn't that complicated, but here is the TypeScriptToLua version...

```ts
//@ts-expect-error package
const path = [...package.path.split(";")];
const debuggerPath = path.filter((path) => path.includes("tomblind.local-lua-debugger"))[0];
print(debuggerPath);
if (debuggerPath != null) {
  const [debuggerModule, err] = loadfile(`${debuggerPath.substr(0, debuggerPath.indexOf("?.lua"))}lldebugger.lua`);
  if (debuggerModule) {
    //@ts-expect-error package
    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
    package.loaded["lldebugger"] = debuggerModule();
  } else print(err);
}

if (os.getenv("LOCAL_LUA_DEBUGGER_VSCODE") == "1") {
  const r = require;
  // eslint-disable-next-line @typescript-eslint/no-var-requires, @typescript-eslint/no-unsafe-assignment
  const lldebugger = r("lldebugger");
  // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-call
  lldebugger.start();
}
```

```lua
--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
require("lualib_bundle")
__TS__SourceMapTraceBack(debug.getinfo(1).short_src, {["4"] = 2,["5"] = 2,["6"] = 2,["7"] = 2,["8"] = 2,["9"] = 3,["10"] = 3,["11"] = 3,["12"] = 3,["13"] = 4,["14"] = 5,["15"] = 6,["16"] = 6,["17"] = 6,["18"] = 6,["19"] = 6,["20"] = 6,["21"] = 6,["22"] = 7,["23"] = 10,["25"] = 11,["28"] = 14,["29"] = 15,["30"] = 17,["31"] = 19});
path = {
    unpack(
        __TS__StringSplit(package.path, ";")
    )
}
debuggerPath = __TS__ArrayFilter(
    path,
    function(____, path) return __TS__StringIncludes(path, "tomblind.local-lua-debugger") end
)[1]
print(debuggerPath)
if debuggerPath ~= nil then
    local debuggerModule, err = loadfile(
        __TS__StringSubstr(
            debuggerPath,
            0,
            (string.find(debuggerPath, "?.lua", nil, true) or 0) - 1
        ) .. "lldebugger.lua"
    )
    if debuggerModule then
        package.loaded.lldebugger = debuggerModule()
    else
        print(err)
    end
end
if os.getenv("LOCAL_LUA_DEBUGGER_VSCODE") == "1" then
    local r = require
    local lldebugger = r("lldebugger")
    lldebugger:start()
end
```

**Comment by astrochili** [comment]
Thanks for the suggestion!

Unfortunately I can't integrate and test this until https://github.com/defold/defold/issues/5949 is solved, because I migrated to Apple M1. Looking forward to Defold updates.

**Comment by thejustinwalsh** [comment]
https://github.com/ts-defold/defold-lldebugger/tree/extension

**Comment by thejustinwalsh** [comment]
Also check out my other extension that I made while not knowing about @thesofakillers version of the pbtxt extension.
https://github.com/thejustinwalsh/textproto-grammar 🤣

**Comment by astrochili** [comment]
Great work!

There is still https://github.com/defold/defold/issues/5703. TypeScriptToLua generates own `require()` function. I renamed it to `include()`. How do you solved it without editing **lldebugger.lua**?

**Comment by astrochili** [comment]
Commits https://github.com/astrochili/defold-vscode-guide/commit/eabade6015beb0b85fb54a41c3b3088597ea5f13 and https://github.com/astrochili/defold-vscode-guide/commit/4a92db636db571cd1598c826cfc58ebdb6749ef0 are done. Thanks for the idea!

**Comment by astrochili** [comment]
@thejustinwalsh btw, I updated script and now it uses `java`, `bob`, `dmengine` and `ddls` from the Defold Editor directly. Awesome.

**Comment by thejustinwalsh** [comment]
Amazing! I’ll take a look. May also make a VSCode extension that just does all this as a task config. :)
