### ISSUE TITLE
JDK folder name does not match

### ISSUE THREAD

**Issue by forge18** [astrochili/defold-vscode-guide#10]
First off, thank you for this template, it has been really helpful. 

As for the issue I found... The JDK folder in the most recent version of Defold is labeled "jdk11.0.15+10". The defold.sh file in this example project has the JDK folder listed as "jdk11.0.1-p1". This is causing a build error that prevents the project from being opened from VS Code.

**Comment by astrochili** [comment]
Oh, thanks! Is it enough to just edit the path?
