### ISSUE TITLE
Question about dependencies autocompletion support

### ISSUE THREAD

**Issue by MadGeorge** [astrochili/defold-vscode-guide#12]
Hello. I failed to setup autocompletion for dependencies linked from the Defold editor project settings.

I have a new empty project with single dependency 
<img width="858" alt="Screen Shot 2022-11-16 at 14 25 39" src="https://user-images.githubusercontent.com/25031713/202155881-9cba6b81-9d5c-442e-82c0-eb27960b950c.png">

The integration was setup step by step from this guide.   
Following section [Library](https://github.com/astrochili/defold-vscode-guide#libraries) from the readme archive in the `.internal/lib/` where unpacked. 

But autocompletion still does not work for the dependency
<img width="913" alt="Screen Shot 2022-11-16 at 14 21 04" src="https://user-images.githubusercontent.com/25031713/202157171-ad014947-5ed8-4c0f-b7bb-7e2d3a6a12a6.png">

I assume my setup is mostly correct since i have autocompletion for local Defold API and local code
<img width="1074" alt="Screen Shot 2022-11-16 at 14 03 24" src="https://user-images.githubusercontent.com/25031713/202157479-8d75ac83-07e0-4600-b98f-272cba2cf916.png">

and dependency by itself is valid since i have autocompletion in the Defold editor  
(but it does not autocomplete for local sources 😬)
<img width="918" alt="Screen Shot 2022-11-16 at 14 21 41" src="https://user-images.githubusercontent.com/25031713/202157691-a8f6b1d7-648b-4744-80d8-3e1335540e34.png">

I tried to move unzipped sources folder to the root of `.internal` directory without success.

Did i miss something? Does some one managed to resolve a similar issue?  

Here is the complete project archive
[VSIntegration.zip](https://github.com/astrochili/defold-vscode-guide/files/10020789/VSIntegration.zip)

OS: macOS 12.6
Defold Editor: 1.3.7
Dependency: https://github.com/rgrams/rendercam (no native plugins)

Thank you for this guide and sources buy the way.

**Comment by astrochili** [comment]
First of all, thank you for a detailed description of the problem. That's really cool.

I downloaded your example and got autofill right away, so everything seems to be fine in the project itself.

![image1](https://user-images.githubusercontent.com/4752473/202241220-bb6ac7e8-9aac-43b3-a6a7-91fdf92dc3cb.png)

Also tried to clear the general settings json, but everything works again.

![image2](https://user-images.githubusercontent.com/4752473/202241854-3f8a0971-9d42-4697-b7d2-c6bcd7b085da.png)

Can we compare versions of tools? I have:

- VSCode 1.72.2
- Local Lua Debugger by Tom Blind 0.3.3
- Lua by sumneko 3.6.3

**Comment by MadGeorge** [comment]
> I downloaded your example and got autofill right away
Ok, that's was surprising. 

I have no `Local Lua Debugger` but `Lua MobDebug adapter`.
Tools versions i have are:

- VSCode  1.73.1
- Lua by sumneko v3.6.3
- Lua MobDebug adapter v0.0.5 
 
I will try to remove ModDebug and install Local Lua Debugger.

**Comment by MadGeorge** [comment]
Looks like uptime in 35 days is not ok for my mac. 
After system restart autocompletion work now even with MobDebug installed instead of Local Lua Debugger.

Thank you for your quick assistance and excuse for troubling. The guide is fine, it's just me again.

**Comment by astrochili** [comment]
Glad it worked out!

By the way, what do you use the Lua MobDebug adapter extension for? I see it's something new, did you manage to run it with Defold?

**Comment by MadGeorge** [comment]
It's an attempt to setup the built-in mobdebug in the VSCode. Not successful yet.
