### ISSUE TITLE
defold-api on sumneko

### ISSUE THREAD

**Issue by selimanac** [astrochili/defold-vscode-guide#13]
This is just a note for [Defold API ](https://github.com/astrochili/defold-vscode-guide#defold-api)files...

There is a build-in support for Defold API on  sumneko/lua-language-server. I'm not sure if it is up to date but it can be used:
https://github.com/sumneko/lua-language-server/wiki/Libraries

```json
"Lua.workspace.library": [
        "${3rd}/Defold/library"
    ]
```

**Comment by astrochili** [comment]
Interesting! These files based on [the fork](https://github.com/SalavatR/defold-api-lua-language-server) of original [defold-api-emmylua](https://github.com/d954mas/defold-api-emmylua). Files looks a bit [rewritten and updated](https://github.com/d954mas/defold-api-emmylua/compare/master...SalavatR:defold-api-lua-language-server:master) to support Defold 1.3.7 and lua-language-server.

So this process looks like @SalavatR updates his fork and commits changes to the lua-language-server repository by @sumneko. Sounds no less and no more stable than the current scheme.

I also want to take into account that perhaps the generation of the headers can be [provided by Defold](https://forum.defold.com/t/defold-editor-should-drop-the-code-editor/72368/34) in the future.

**Comment by astrochili** [comment]
Update. LuaLS decided to remove {3rd} libraries support due the upcoming VSCode addons.
https://github.com/LuaLS/lua-language-server/discussions/1950

**Comment by astrochili** [comment]
Close because the best way to get defied api is to get it from the current Defold Editor folder. See https://github.com/astrochili/defold-vscode-guide/issues/17.

**Comment by astrochili** [comment]
Closed because the best way to get api headers is to generate them from the current Defold Editor folder api json data. See https://github.com/astrochili/defold-vscode-guide/issues/17.
