### ISSUE TITLE
this error ".vscode/defold.sh: line 2: $'\r': command not found" occured when i run the game

### ISSUE THREAD

**Issue by eldon97** [astrochili/defold-vscode-guide#21]
![image](https://user-images.githubusercontent.com/19554521/233845322-45c9cc9c-a67f-4289-af69-156747b05f0b.png)
but the game is running fine

**Comment by astrochili** [comment]
Interesting. It's just a line break character. It can't be a script error by definition, some peculiarity of Windows + bash as always.

Take a look at https://stackoverflow.com/questions/11616835/r-command-not-found-bashrc-bash-profile, maybe there's something useful there.

**Comment by eldon97** [comment]
great, it's solved. thanks
