### ISSUE TITLE
This error occured "java.nio.file.NoSuchFileException: C:\Program%20Files\Defold\packages\defold-1a64dd2dda6107fc68b0055b7ca2168740e83f76.jar"

### ISSUE THREAD

**Issue by eldon97** [astrochili/defold-vscode-guide#22]
i check the file and it's exist exactly at that particular path.
![image](https://user-images.githubusercontent.com/19554521/234461017-ab2a28ec-3cb3-4f55-b358-517cf32142e0.png)

**Comment by astrochili** [comment]
Unfortunately, the path to Defold Editor cannot contain spaces right now. This is caused by the fact that bob cannot be run with spaces, see defold/defold/#593

**Comment by astrochili** [comment]
It I see that the Defold issue is closed two months ago.

Try update Defold to the last version, it can help.

**Comment by eldon97** [comment]
great, finally it's all working fine. it solved by updating Defold. thanks
