### ISSUE TITLE
someone can help me

### ISSUE THREAD

**Issue by Antonygamergod** [astrochili/defold-vscode-guide#24]
how i solve this

.vscode/defold.sh: line 330: .exe: command not found
cp: cannot stat './build/temp/_unpack/x86_64-win32/bin/OpenAL32.dll': No such file or directory
.vscode/defold.sh: line 341: .exe: command not found
cp: cannot stat './build/temp/_unpack/x86_64-win32/bin/wrap_oal.dll': No such file or directory
# Launching
$ ./build/x86_64-win32/dmengine ./build/default/game.projectc

.vscode/defold.sh: line 366: ./build/x86_64-win32/dmengine: No such file or directory

**Comment by astrochili** [comment]
Hello! I saw your screenshot at [the forum](https://forum.defold.com/t/guide-how-to-turn-vscode-into-defold-ide-with-debugger/68002/29?u=astrochili). It contains the `YOUR-DEFOLD-PATH-HERE` phrase. Please edit the defold.sh and paste the Defold path there according the [instruction](https://github.com/astrochili/defold-vscode-guide#defold-path).
