### ISSUE TITLE
Unclear instruction?

### ISSUE THREAD

**Issue by ogrotten** [astrochili/defold-vscode-guide#7]
In the README.md under "Libraries" it says:

> "To help the language server to find external libraries and parse their headers you need to unarchive the *.zip files in the `.internal/lib/` folder."

Where is the ` .internal/lib/` folder spoken of in this instruction?

**Comment by astrochili** [comment]
`.internal/lib/` in the project root folder. This folder appears after the external libraries are installed.

If there are no external libraries in the project, there is no `.internal/lib/` folder.
